### ISSUE TITLE
return json in utf-8

### ISSUE THREAD

**Issue by busla** [scrapinghub/scrapyrt#46] opened 2016-12-11 15:22 UTC
My spider response data is returned in unicode. What needs to be done in order for it to be returned in utf-8?

Cheers 😄

**Comment by pawelmhm** [comment] 2016-12-22 09:51
sorry I'm not sure if I understand @busla do you mean response in spider callback is unicode? are we not handling uttf-8 properly somewhere? Can you give something to reproduce your problem, some example that shows what you have in mind?

**Comment by pawelmhm** [comment] 2017-03-08 14:15
closing because of no clarification, not sure what the issue is and what we can do to fix it

**Closed by pawelmhm** 2017-03-08 14:15 UTC
