### ISSUE TITLE
Interfacing with scrapyd 

### ISSUE THREAD

**Issue by robinicole** [scrapinghub/scrapyrt#106] opened 2020-03-27 16:41 UTC
I would like to run scrapyrt and scrapyd nect to each other by adding a scrapyrt target in scrapyd: 
```
[services]
schedule.json     = scrapyd.webservice.Schedule
cancel.json       = scrapyd.webservice.Cancel
addversion.json   = scrapyd.webservice.AddVersion
listprojects.json = scrapyd.webservice.ListProjects
listversions.json = scrapyd.webservice.ListVersions
listspiders.json  = scrapyd.webservice.ListSpiders
delproject.json   = scrapyd.webservice.DeleteProject
delversion.json   = scrapyd.webservice.DeleteVersion
listjobs.json     = scrapyd.webservice.ListJobs
daemonstatus.json = scrapyd.webservice.DaemonStatus
scrapyrt.json =  scrapyrt.resources.CrawlResource
```
But when I try to run it, the project loaded in scrapyd is not loaded in scrapyrt, would you have an idea on how to wrap the CrawlRessource class to make it compatible with scrapy services

**Comment by pawelmhm** [comment] 2021-09-22 13:25
Have you tried just running both services together behind some web server and just routing traffic to scrapyrt or scrapyd based on path? You can configure that with nginx. For example: scrapyd running on port 9000, nginx directing all paths listed to port 9000, scrapyrt running on port 9001 nginx routing traffic to some path to scrapyrt?

I think this is more about documentation, not a bug or requested feature so I'll close this issue. If you feel there is something can be done in scrapyrRT or see some bug please reopen it.

**Closed by pawelmhm** 2021-09-22 13:25 UTC
